### ISSUE TITLE
Longer Token

### ISSUE THREAD

**Issue by ritotombe** [trolster/udex-chrome-extension#1]
I have 153 character token so it cannot be validated.

**Comment by trolster** [comment]
Hi @ritotombe, that's surprising. I'll see if I can't update it today to accept longer tokens.

**Comment by trolster** [comment]
Hi @ritotombe, I was unaware that tokens could be shorter or longer, so thanks for letting me know. I've pushed a fix for the issue. Let me know if it works for you.

**Comment by ritotombe** [comment]
Working now man!
Appreciate it.
